### ISSUE TITLE
The first eg issues...

### ISSUE THREAD

**Issue by mark-summerfield** [stevej2608/oppen-pretty-printer#4]
I've now realised that the output of the first example is as intended.

But it doesn't seem right; surely the whole point of the eg is to show a simple pprint with a begin/end block?

I changed the first example to this:
```python
tokens = [
    T.BEGIN(),
    T.STRING("begin"),
    T.LINEBREAK,
    T.STRING("x"),
    T.BREAK(), T.STRING(":="), T.BREAK(),
    T.STRING("40"),
    T.BREAK(), T.STRING("+"), T.BREAK(),
    T.STRING("2"),
    T.LINEBREAK,
    T.STRING("end"),
    T.END(),
    T.EOF()]
for line in pprint(tokens).splitlines(): print(line)
```
But this surprisingly produces:
```
begin
  x := 40 + 2
  end
```
Well, it is a surpise to me.

**Comment by stevej2608** [comment]
The example in the README is just intended to show basic usage.

I'll add a line to the example that shows the expected output.

Cheers
